import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BellIcon, SearchIcon } from "lucide-react";
import React from "react";
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar.js";
import { Button } from "../ui/button.js";
import { Input } from "../ui/input.js";
export const Navbar = () => {
    return (_jsx("nav", { className: "w-full bg-white border-b border-gray-200 px-8 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-8", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 bg-gradient-to-br from-[#4182f9] to-[#7ba3f7] rounded-lg flex items-center justify-center", children: _jsx("span", { className: "[font-family:'Poppins',Helvetica] font-semibold text-white text-lg", children: "TP" }) }), _jsx("h1", { className: "[font-family:'Poppins',Helvetica] font-semibold text-xl text-black", children: "MediSafe" })] }), _jsxs("div", { className: "flex items-center gap-6 ml-8", children: [_jsx("a", { href: "#", className: "[font-family:'Poppins',Helvetica] font-normal text-base text-[#4182f9] hover:text-[#3671e8] transition-colors", children: "Dashboard" }), _jsx("a", { href: "#", className: "[font-family:'Poppins',Helvetica] font-normal text-base text-gray-600 hover:text-[#4182f9] transition-colors", children: "Profile" }), _jsx("a", { href: "#", className: "[font-family:'Poppins',Helvetica] font-normal text-base text-gray-600 hover:text-[#4182f9] transition-colors", children: "Settings" }), _jsx("a", { href: "#", className: "[font-family:'Poppins',Helvetica] font-normal text-base text-gray-600 hover:text-[#4182f9] transition-colors", children: "Help" })] })] }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsxs("div", { className: "relative", children: [_jsx(SearchIcon, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" }), _jsx(Input, { placeholder: "Search...", className: "pl-10 w-[280px] bg-[#f9f9f9] border-0 rounded-lg h-10 [font-family:'Poppins',Helvetica] font-normal text-sm" })] }), _jsxs(Button, { size: "icon", variant: "ghost", className: "relative w-10 h-10 hover:bg-gray-100 rounded-lg", children: [_jsx(BellIcon, { className: "w-5 h-5 text-gray-600" }), _jsx("span", { className: "absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full" })] }), _jsxs(Avatar, { className: "w-10 h-10 cursor-pointer", children: [_jsx(AvatarImage, { src: "" }), _jsx(AvatarFallback, { className: "bg-[#4182f9] text-white text-sm", children: "U" })] })] })] }) }));
};
//# sourceMappingURL=Navbar.js.map